name: thegorgeousotp
description: The Gorgeous OTP

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  numeric_keyboard: ^1.0.0
  cloud_firestore: ^0.14.3+1
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  animated_text_kit: ^2.2.0

  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4

  cupertino_icons: ^0.1.3
  polygon_clipper: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/